image: aoepeople/carotene-env:1.7.0

stages:
- test
- publish

.prepare-npm: &prepare_npm
  cache:
    paths:
    - .npm
  before_script:
  - export npm_config_cache=$(pwd -P)/.npm
  - npm i

Test Packages:
  stage: test
  <<: *prepare_npm
  script:
  - npm t

Publish Packages:
  stage: publish
  <<: *prepare_npm
  script:
    - npm run publish-packages
  only:
    - /master/
