image: aoepeople/carotene-env:1.7.0

stages:
- test
- publish

.prepare-yarn: &prepare_yarn
  cache:
    paths:
    - .yarn
  before_script:
  - export YARN_CACHE_FOLDER=$(pwd -P)/.yarn
  - yarn

Test Packages:
  stage: test
  <<: *prepare_yarn
  script:
  - yarn test

Publish Packages:
  stage: publish
  <<: *prepare_yarn
  script:
    - yarn publish-packages
  only:
    - /master/
