image: aoepeople/carotene-env:1.7.0

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

stages:
  - setup
  - test
  - publish

Setup:
  stage: setup
  script:
    - yarn

Test Packages:
  stage: test
  script:
    - yarn test

Publish Packages:
  stage: publish
  script:
    - yarn publish-packages
  only:
    - /master/
