# Documentation for the sass-lint Linters is available at:
# https://github.com/sasstools/sass-lint/tree/master/docs/rules

files:
  include: 'src/**/*.s+(a|c)ss'
options:
  max-warnings: 25
rules:
  # Extends
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 0


  # Mixins
  mixins-before-declarations:
    - 2

  # Line Spacing
  one-declaration-per-line: 2
  empty-line-between-blocks:
    - 2
    - ignore-single-line-rulesets: false
  single-line-per-selector: 2

  # Nesting
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  nesting-depth:
    - 1
    - max-depth: 4

  # Name Formats
  class-name-format:
    - 2
    - convention: camelcase
  function-name-format:
    - 2
    - convention: camelcase
  id-name-format:
    - 2
    - convention: camelcase
  mixin-name-format:
    - 2
    - convention: camelcase
  placeholder-name-format:
    - 2
    - convention: camelcase
  variable-name-format:
    - 2
    - convention: camelcase

  # Misc
  property-sort-order: 0
  no-transition-all: 0
  indentation:
    - 0
